# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Jan 26 11:08:14 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(761, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setCursor(QtCore.Qt.ArrowCursor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(66, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.edt_apikey = QtGui.QLineEdit(self.centralwidget)
        self.edt_apikey.setObjectName("edt_apikey")
        self.horizontalLayout_2.addWidget(self.edt_apikey)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(66, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.edt_apisecret = QtGui.QLineEdit(self.centralwidget)
        self.edt_apisecret.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.edt_apisecret.setObjectName("edt_apisecret")
        self.horizontalLayout_3.addWidget(self.edt_apisecret)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(66, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.edt_bucket_name = QtGui.QLineEdit(self.centralwidget)
        self.edt_bucket_name.setObjectName("edt_bucket_name")
        self.horizontalLayout_4.addWidget(self.edt_bucket_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(66, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.edt_prefix = QtGui.QLineEdit(self.centralwidget)
        self.edt_prefix.setObjectName("edt_prefix")
        self.horizontalLayout_5.addWidget(self.edt_prefix)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.table_widget = QtGui.QTableWidget(self.centralwidget)
        self.table_widget.setMinimumSize(QtCore.QSize(340, 397))
        self.table_widget.setRowCount(0)
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(2)
        self.table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.table_widget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_select_files = QtGui.QPushButton(self.centralwidget)
        self.btn_select_files.setObjectName("btn_select_files")
        self.verticalLayout.addWidget(self.btn_select_files)
        self.btn_select_dir = QtGui.QPushButton(self.centralwidget)
        self.btn_select_dir.setObjectName("btn_select_dir")
        self.verticalLayout.addWidget(self.btn_select_dir)
        self.btn_upload = QtGui.QPushButton(self.centralwidget)
        self.btn_upload.setObjectName("btn_upload")
        self.verticalLayout.addWidget(self.btn_upload)
        self.btn_clear = QtGui.QPushButton(self.centralwidget)
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout.addWidget(self.btn_clear)
        self.btn_exit = QtGui.QPushButton(self.centralwidget)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 17))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelect_Files = QtGui.QAction(MainWindow)
        self.actionSelect_Files.setObjectName("actionSelect_Files")
        self.actionSelect_Directories = QtGui.QAction(MainWindow)
        self.actionSelect_Directories.setObjectName("actionSelect_Directories")
        self.actionUpload = QtGui.QAction(MainWindow)
        self.actionUpload.setObjectName("actionUpload")
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionLoad_Config = QtGui.QAction(MainWindow)
        self.actionLoad_Config.setObjectName("actionLoad_Config")
        self.actionSave_Config = QtGui.QAction(MainWindow)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.menuFile.addAction(self.actionSelect_Files)
        self.menuFile.addAction(self.actionSelect_Directories)
        self.menuAction.addAction(self.actionUpload)
        self.menuAction.addAction(self.actionClear)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionLoad_Config)
        self.menuAction.addAction(self.actionSave_Config)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Qiniu CDN Upload Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "API KEY    ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "API SECRET ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Bucket Name", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_bucket_name.setToolTip(QtGui.QApplication.translate("MainWindow", "Bucket_name of your CDN.", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_bucket_name.setStatusTip(QtGui.QApplication.translate("MainWindow", "Bucket_name of your CDN.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Prefix     ", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_prefix.setStatusTip(QtGui.QApplication.translate("MainWindow", "Prefix, will be applied to all files.", None, QtGui.QApplication.UnicodeUTF8))
        self.table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Content", None, QtGui.QApplication.UnicodeUTF8))
        self.table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Progress     ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_files.setToolTip(QtGui.QApplication.translate("MainWindow", "Select files to upload.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_files.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select files to upload.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_files.setText(QtGui.QApplication.translate("MainWindow", "Select Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_dir.setToolTip(QtGui.QApplication.translate("MainWindow", "Select directories to upload.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_dir.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select directories to upload.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_dir.setText(QtGui.QApplication.translate("MainWindow", "Select Dirs", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_upload.setToolTip(QtGui.QApplication.translate("MainWindow", "Upload files and directories in table content.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_upload.setStatusTip(QtGui.QApplication.translate("MainWindow", "Upload files and directories in table content.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_upload.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setToolTip(QtGui.QApplication.translate("MainWindow", "Reset files and directories.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setStatusTip(QtGui.QApplication.translate("MainWindow", "Reset files and directories.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_exit.setToolTip(QtGui.QApplication.translate("MainWindow", "Exit.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_exit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Exit.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAction.setTitle(QtGui.QApplication.translate("MainWindow", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_Files.setText(QtGui.QApplication.translate("MainWindow", "Select Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_Directories.setText(QtGui.QApplication.translate("MainWindow", "Select Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpload.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Config.setText(QtGui.QApplication.translate("MainWindow", "Load Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Config.setStatusTip(QtGui.QApplication.translate("MainWindow", "Load Config from ini file.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setText(QtGui.QApplication.translate("MainWindow", "Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save config to ini file.", None, QtGui.QApplication.UnicodeUTF8))

import baniugui_rc
